#######################################################
# GENERAL ALIAS'S
#######################################################
# To temporarily bypass an alias, we precede the command with a \
# EG: the ls command is aliased, but to use the normal ls command you would type \ls

# Sudo preserving user's envvars
alias sude='sudo -E'
alias firefox='cd ~/ && nohup firefox -P &'
alias heroic='cd ~/ && nohup heroic &'
alias discord='cd ~/ && nohup discord &'
alias steam='cd ~/ && nohup steam &'
alias lutris='cd ~/ && nohup lutris &'
alias thunar='cd ~/ && nohup thunar &'
alias obsidian='cd ~/ && nohup obsidian &'
alias bitwarden='cd ~/ && nohup bitwarden-desktop &'
alias virt-manager='cd ~/ && nohup virt-manager &'
alias virtualbox='cd ~/ && nohup virtualbox &'
alias libreoffice='cd ~/ && nohup libreoffice &'
alias office='cd ~/ && nohup libreoffice &'
alias bottles='cd ~/ && nohup bottles &'
alias gnuemacsd='cd ~/ && nohup emacs --daemon &'
alias doomemacsd='cd ~/ && nohup emacs --with-profile=doom --daemon &'
alias gnuemacs='cd ~/ && nohup emacsclient -c -s gnu -a emacs &'
alias doomemacs='cd ~/ && nohup emacsclient -c -s doom -a emacs &'
alias spacemacs='cd ~/ && nohup emacs --with-profile=space &'
alias stemacs='cd ~/ && nohup emacs --with-profile=stemacs &'
alias whatsapp='cd ~/ && nohup whatsapp-for-linux &'
alias eclipse='cd ~/ && nohup eclipse &'
alias qalculate='cd ~/ && nohup qalculate-gtk &'
alias godot='cd ~/ && nohup godot &'
alias blender='cd ~/ && nohup blender &'
alias sudenvim='sudo -E nvim'
alias zoom='cd ~/ && nohup zoom &'
alias torbrowser='cd ~/ && nohup torbrowser-launcher &'
alias syncthing='cd ~/ && nohup syncthing &'
alias yata='cd ~/ && nohup gtk-launch yata &'
alias gdlauncher='cd ~/ && nohup gdlauncher &'
alias codium='cd ~/ && nohup codium --password-store="kwallet5" &'
alias trash='gio trash'
alias rmt='gio trash'

# Neverwinter Nights: Enhanced Edition
alias tlkedit='cd ~/ && nohup gtk-launch tlkedit &'
alias nwnexplorer='cd ~/ && nohup gtk-launch nwnexplorer &'
alias scriptgenerator='cd ~/ && nohup gtk-launch scriptgenerator &'
alias 2dacombinulator='cd ~/ && nohup gtk-launch 2dacombinulator &'
alias nwhak='cd ~/ && nohup gtk-launch nwhak &'
alias nwtoolset='cd ~/ && nohup gtk-launch nwtoolset &'
alias toolset='cd ~/ && nohup gtk-launch nwtoolset &'
alias fix2da='cd ~/ && gtk-launch fix2da &'
alias tidy2da='cd ~/ && gtk-launch tidy2da &'
alias nwsyncUpdate='sudo sh /mnt/SSD_1TB_WORK/WoSEE/Tools/nwsync/nwsync-update.sh'
alias uploadNWSync='sh /mnt/SSD_1TB_WORK/WoSEE/Tools/nwsync/uploadNWSync.sh'
alias modStart='cd /mnt/SSD_1TB_WORK/WoSEE/Server && sh /mnt/SSD_1TB_WORK/WoSEE/Server/mod-start_ptr.sh'
alias modStop='cd /mnt/SSD_1TB_WORK/WoSEE/Server && sh /mnt/SSD_1TB_WORK/WoSEE/Server/mod-stop_ptr.sh'
alias modEnable='cd /mnt/SSD_1TB_WORK/WoSEE/Server && sh /mnt/SSD_1TB_WORK/WoSEE/Server/mod-enable_ptr.sh'
alias modDisable='cd /mnt/SSD_1TB_WORK/WoSEE/Server && sh /mnt/SSD_1TB_WORK/WoSEE/Server/mod-disable_ptr.sh'
alias modStatus='cd /mnt/SSD_1TB_WORK/WoSEE/Server && sh /mnt/SSD_1TB_WORK/WoSEE/Server/mod-status_ptr.sh'
alias modSavechars='cd /mnt/SSD_1TB_WORK/WoSEE/Server && sh /mnt/SSD_1TB_WORK/WoSEE/Server/mod-savechars.sh'

# Monero
alias monero='monerod --block-sync-size 10 --db-sync-mode fastest:sync:8750'
