alias firefox='cd ~/ && nohup firefox -P &'
alias heroic='cd ~/ && nohup heroic &'
alias discord='cd ~/ && nohup discord &'
alias steam='cd ~/ && nohup steam &'
alias lutris='cd ~/ && nohup lutris &'
alias thunar='cd ~/ && nohup thunar &'
alias sude='sudo -E'
alias obsidian='cd ~/ && nohup obsidian &'
alias bitwarden='cd ~/ && nohup bitwarden-desktop &'
alias virt-manager='cd ~/ && nohup virt-manager &'
alias virtualbox='cd ~/ && nohup virtualbox &'
alias libreoffice='cd ~/ && nohup libreoffice &'
alias office='cd ~/ && nohup libreoffice &'
alias bottles='cd ~/ && nohup bottles &'
alias gnuemacsd='cd ~/ && nohup emacs --daemon &'
alias doomemacsd='cd ~/ && nohup emacs --with-profile=doom --daemon &'
alias gnuemacs='cd ~/ && nohup emacsclient -c -s gnu -a emacs &'
alias doomemacs='cd ~/ && nohup emacsclient -c -s doom -a emacs &'
alias spacemacs='cd ~/ && nohup emacs --with-profile=space &'
alias stemacs='cd ~/ && nohup emacs --with-profile=stemacs &'
alias whatsapp='cd ~/ && nohup whatsapp-for-linux &'
alias eclipse='cd ~/ && nohup eclipse &'
alias qalculate='cd ~/ && nohup qalculate-gtk &'
alias godot='cd ~/ && nohup godot &'
alias blender='cd ~/ && nohup blender &'
alias stvim='NVIM_APPNAME=stvim nvim'
alias nvchad='NVIM_APPNAME=nvchad nvim'
alias zoom='cd ~/ && nohup zoom &'
alias torbrowser='cd ~/ && nohup torbrowser-launcher &'
alias syncthing='cd ~/ && nohup syncthing &'
