# See https://wiki.hyprland.org/Configuring/Environment-variables/

# Themes
env=XCURSOR_THEME,Catppuccin-Mocha-Mauve-Cursors
env=XCURSOR_SIZE,48
env=HYPRCURSOR_SIZE,48
env=GTK_THEME,Catppuccin-Mocha-Standard-Mauve-Dark

# NVidia Specific
env=__GL_GSYNC_ALLOWED,1
env=LIBVA_DRIVER_NAME,nvidia
env=XDG_SESSION_TYPE,wayland
env=GBM_BACKEND,nvidia-drm # May crash firefox.
env=__GLX_VENDOR_LIBRARY_NAME,nvidia # May prevent screen sharing on Discord or Zoom.
#env=__NV_PRIME_RENDER_OFFLOAD,1 # For laptops with AMD/Intel's iGPU and NVidia's dGPU

env=NVD_BACKEND,direct # VA-API Hardware Acceleration
env=ELECTRON_OZONE_PLATFORM_HINT,auto # Fixes flickering in Electron/CEF Apps

env=EGL_PLATFORM,wayland;x11

# Vulkan
env=VK_DRIVER_FILES,/usr/share/vulkan/icd.d/nvidia_icd.json
env=VK_LAYER_PATH,/usr/share/vulkan/explicit_layer.d

# Forcing Wayland
env=GDK_BACKEND,wayland,x11,* # Can prevent programs from starting (e.g. chromium and electron apps). This should be set per app instead of globally.
env=SDL_VIDEODRIVER,wayland # Run SDL2 apps on Wayland. Can prevent programs from starting old sdl games.
env=CLUTTER_BACKEND,wayland # Force Clutter apps to use Wyaland. Clutter package is already Wayland enabled though.

env=QT_AUTO_SCREEN_SCALE_FACTOR,1 # (https://doc.qt.io/qt-5/highdpi.html) enables automatic scaling, based on the monitor’s pixel density
env=QT_STYLE_OVERRIDE,kvantum
env=QT_QPA_PLATFORMTHEME,qt5ct;qt6ct # Make QT applications pick theme from qt6ct, fallback to qt5ct, use with kvantum
env=QT_QPA_PLATFORM,wayland;xcb # Use Wayland, fall back to X11. Already set in Hyprstart

# Usually there are detected and set automatically, not a bad idea to excplicity set them though.
env=XDG_CURRENT_DESKTOP,hyprland
env=XDG_SESSION_DESKTOP,hyprland

# .NET
# env=DOTNET_SYSTEM_GLOBALIZATION_INVARIANT,1 # May crash some programs
env=DOTNET_CLI_TELEMETRY_OPTOUT,1
env=DOTNET_ROOT,$HOME/.dotnet

env=FrameworkPathOverride,/lib/mono/4.8-api

# Misc
env=XDG_CONFIG_HOME,$HOME/.config
env=XDG_SCREENSHOT_DIR,$HOME/Pictures/Grim
env=XDG_DATA_DIRS,/var/lib/flatpak/exports/share:$HOME/.local/share/flatpak/exports/share:$XDG_DATA_DIRS

# text editor
env=SUDO_EDITOR,nvim
env=EDITOR,nvim
env=VISUAL,nvim

#browser
env=BROWSER,firedragon
#terminal
env=TERM,kitty
#mail
env=MAIL,flatpak run org.mozilla.Thunderbird
