# See https://wiki.hyprland.org/Configuring/Environment-variables/
env = XCURSOR_THEME,Catppuccin-Mocha-Mauve-Cursors
env = XCURSOR_SIZE,48
env = HYPRCURSOR_SIZE,48
env = GTK_THEME,Catppuccin-Mocha-Standard-Mauve-Dark

# NVidia Specific
env = __GLX_VENDOR_LIBRARY_NAME,nvidia
env = __GL_GSYNC_ALLOWED,1
env = LIBVA_DRIVER_NAME,nvidia
env = GBM_BACKEND,nvidia-drm
env = NVD_BACKEND,direct
env = VK_ICD_FILENAMES,/usr/share/vulkan/icd.d/nvidia_icd.json

env = VK_LAYER_PATH,/usr/share/vulkan/explicit_layer.d

env = EGL_PLATFORM,wayland;x11

env = NVD_BACKEND,direct # VA-API Hardware Acceleration
env = ELECTRON_OZONE_PLATFORM_HINT,auto # Fixes flickering in Electron/CEF Apps

env = QT_STYLE_OVERRIDE,kvantum
env = QT_QPA_PLATFORMTHEME,qt5ct;qt6ct
env = QT_QPA_PLATFORM,wayland;xcb

# env = GDK_BACKEND,wayland;x11 # Can prevent programs from starting (e.g. chromium and electron apps). This should be set per app instead of globally.
# env = CLUTTER_BACKEND,wayland # this can prevent programs from starting. This should be set per app instead of globally.
# env = SDL_VIDEODRIVER,wayland # Can prevent programs from starting old sdl games. This should be set per app instead of globally.

# env = DOTNET_SYSTEM_GLOBALIZATION_INVARIANT,1
env = DOTNET_CLI_TELEMETRY_OPTOUT,1
env = DOTNET_ROOT,$HOME/.dotnet

env = XDG_CONFIG_HOME,$HOME/.config
env = XDG_SCREENSHOT_DIR,$HOME/Pictures/Grim/

env = FrameworkPathOverride,/lib/mono/4.8-api

env = XDG_CONFIG_HOME,$HOME/.config
env = XDG_SCREENSHOT_DIR,$HOME/Pictures/Grim
env = XDG_DATA_DIRS,/var/lib/flatpak/exports/share:$HOME/.local/share/flatpak/exports/share:$XDG_DATA_DIRS
