source-file ~/dotfiles/.config/tmux/tmux.reset.conf
set-option -g default-terminal "screen-256color"
set-option -sa terminal-overrides ",xterm-256color:RGB"

# Set prefix
# unbind C-b
set -g prefix M-space
# bind M-space send-prefix
set -g base-index 1                 # Start indexing windows at 1 instead of 0
set -g detach-on-destroy off        # don't exit from tmux when closing a session
set -sg escape-time 0               # Zero-out escape time delay
set -g history-limit 100000         # Increase history limit (from 2.000)
set -g renumber-windows on          # Renumber all windows when any window is closed
set -g set-clipboard on             # use system clipboard
set -g status-position bottom       # macOS / darwin style
set -g default-terminal "${TERM}"
setw -g mode-keys vi
set -g pane-base-index 1
setw -g pane-base-index 1
set -g pane-active-border-style 'fg=magenta,bg=default'
set -g pane-border-style 'fg=brightblack,bg=default'

set -g default-command /bin/bash
set -g default-shell /bin/bash
set -g mouse on
set -sg status-interval 1

set -g @fzf-url-fzf-options '-p 60%,30% --prompt="   " --border-label=" Open URL "'
set -g @fzf-url-history-limit '2000'

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-yank'
# set -g @plugin 'tmux-plugins/tmux-resurrect' # Persist tmux sessions after reboot
# set -g @plugin 'tmux-plugins/tmux-continuum' # Auto-save tmux sessions every X mins look below
set -g @plugin 'fcsonline/tmux-thumbs'
set -g @plugin 'sainnhe/tmux-fzf'
set -g @plugin 'wfxr/tmux-fzf-url'
set -g @plugin 'omerxx/catppuccin-tmux'
set -g @plugin 'omerxx/tmux-sessionx'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'tmux-plugins/tmux-prefix-highlight'
set -g @plugin 'tmux-plugins/tmux-cpu'
set -g @plugin 'soyuka/tmux-current-pane-hostname'
# set -g @plugin ''

set -g @sessionx-bind 'o'
set -g @sessionx-x-path '~/dotfiles'
set -g @sessionx-window-height '85%'
set -g @sessionx-window-width '75%'
set -g @sessionx-zoxide-mode 'on'
set -g @sessionx-filter-current 'false'
set -g @sessionx-preview-enabled 'true'
# set -g @continuum-restore 'on'
# set -g @resurrect-strategy-nvim 'session'
set -g @catppuccin_flavour 'mocha'
set -g @catppuccin_window_left_separator ""
set -g @catppuccin_window_right_separator " "
set -g @catppuccin_window_middle_separator " █"
set -g @catppuccin_window_number_position "right"
set -g @catppuccin_window_default_fill "number"
set -g @catppuccin_window_default_text "#W"
set -g @catppuccin_window_current_fill "number"
set -g @catppuccin_window_current_text "#W#{?window_zoomed_flag,(),}"
set -g @catppuccin_status_modules_right "cpu directory date_time"
set -g @catppuccin_status_modules_left "application session host user"
set -g @catppuccin_status_left_separator  " "
set -g @catppuccin_status_right_separator " "
set -g @catppuccin_status_middle_separator " █"
set -g @catppuccin_status_right_separator_inverse "no"
set -g @catppuccin_status_fill "icon"
set -g @catppuccin_status_connect_separator "no"
set -g @catppuccin_directory_text "#{b:pane_current_path}"
set -g @catppuccin_date_time_text "%d-%m-%Y %H:%M:%S"

if "test ! -d ~/.config/tmux/plugins/tpm" \
   "run 'git clone https://github.com/tmux-plugins/tpm ~/.config/tmux/plugins/tpm && ~/.config/tmux/plugins/tpm/bin/install_plugins'"

run '~/.config/tmux/plugins/tpm/tpm'
