[Interface]
PrivateKey = ###PrivateKey_of_the_Client
Address = ###IP_VPN_for_the_Client
DNS = 1.1.1.1, 8.8.8.8, 4.2.2.1, 1.0.0.1, 8.8.4.4, 4.2.2.6

[Peer]
PublicKey = ###PublicKey_of_the_Server
Endpoint = ###IP_of_the_server:51420
AllowedIPs = ###Allow_all_traffic
