[Interface]
Address = 10.20.10.1/32
ListenPort = 51820
PrivateKey = ###YourPrivateKey

PostUp = iptables -A FORWARD -i wg0 -j ACCEPT
PostUp = iptables -t nat -A POSTROUTING -o ###Your_Network_Interface_Name -j MASQUERADE
PostDown = iptables -D FORWARD -i wg0 -j ACCEPT
PostDown = iptables -t nat -D POSTROUTING -o ####Your_Network_Interface_Name -j MASQUERAD
