#!/bin/sh
cd ~
# user preferred settings

# Theme
export XCURSOR_SIZE=48
export XCURSOR_THEME=Catppuccin-Mocha-Mauve-Cursors
export GTK_THEME=Catppuccin-Mocha-Standard-Mauve-Dark

export FrameworkPathOverride=/lib/mono/4.8-api
export __GLX_VENDOR_LIBRARY_NAME=nvidia
export VK_ICD_FILENAMES=/usr/share/vulkan/icd.d/nvidia_icd.json
export VK_LAYER_PATH=/usr/share/vulkan/explicit_layer.d

# text editor
export SUDO_EDITOR=nvim
export EDITOR=nvim
export VISUAL=nvim

#browser
export BROWSER=firedragon
#terminal
export TERM=kitty
#mail
export MAIL=thunderbird

# To have colors for ls and all grep commands such as grep, egrep and zgrep
export CLICOLOR=1
export LS_COLORS='no=00:fi=00:di=00;34:ln=01;36:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arj=01;31:*.taz=01;31:*.lzh=01;31:*.zip=01;31:*.z=01;31:*.Z=01;31:*.gz=01;31:*.bz2=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.jpg=01;35:*.jpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.avi=01;35:*.fli=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.ogg=01;35:*.mp3=01;35:*.wav=01;35:*.xml=00;31:'

# Color for manpages in less makes manpages a little easier to read
export LESS_TERMCAP_mb=$'\E[01;31m'
export LESS_TERMCAP_md=$'\E[01;31m'
export LESS_TERMCAP_me=$'\E[0m'
export LESS_TERMCAP_se=$'\E[0m'
export LESS_TERMCAP_so=$'\E[01;44;33m'
export LESS_TERMCAP_ue=$'\E[0m'
export LESS_TERMCAP_us=$'\E[01;32m'

export DOTNET_CLI_TELEMETRY_OPTOUT=1
export DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=1
export DOTNET_ROOT=$HOME/.dotnet

export CARGO_INSTALL_ROOT=$HOME/.cargo

export PATH="$PATH:$CARGO_INSTALL_ROOT/bin"
export PATH="$PATH:$HOME/.local/bin"
export PATH="$PATH:$HOME/.dotnet/tools"
export PATH="$PATH:$HOME/dotfiles/emacs/doom/doomemacs/bin"
export PATH="$PATH:/usr/local"
export LOCALE_ARCHIVE=/usr/lib/locale/locale-archive

export XDG_CONFIG_HOME="$HOME"/.config
export QT_STYLE_OVERRIDE=kvantum
export QT_QPA_PLATFORMTHEME='qt5ct:qt6ct'
# export QT_QPA_PLATFORMTHEME=gtk3

export PATH="$HOME/.nimble/bin":$PATH
export NWN_ROOT='/mnt/SSD_1TB_GAMES/SteamLibrary/steamapps/common/Neverwinter Nights'
export NWN_HOME='/mnt/SSD_1TB_WORK/WoSEE/Documents'

export GPG_TTY=$(tty)

# fzf theme
export FZF_DEFAULT_OPTS=" \
--color=bg+:#313244,bg:#1e1e2e,spinner:#f5e0dc,hl:#f38ba8 \
--color=fg:#cdd6f4,header:#f38ba8,info:#cba6f7,pointer:#f5e0dc \
--color=marker:#f5e0dc,fg+:#cdd6f4,prompt:#cba6f7,hl+:#f38ba8"

export FZF_DEFAULT_COMMAND='fd --hidden --strip-cwd-prefix --exclude .git'
export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"
export FZF_ALT_C_COMMAND="$FZF_DEFAULT_COMMAND --type d"

export FZF_CTRL_T_OPTS="--preview 'bat -n --color=always --line-range :500 {}'"
export FZF_ALT_C_OPTS="--preview 'eza -al --color=always --group-directories-first --icons --git | head -200'"

# Bat theme
export BAT_THEME='Catppuccin Mocha'

export LSP_USE_PLISTS=true

export DOOMDIR="$HOME/dotfiles/emacs/doom/.doom.d"
export STEMACSDIR="$HOME/dotfiles/emacs/stemacs/.stemacs.d"
