# ┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
# ┃                    Autostart Configuration                  ┃
# ┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛

source = ~/.config/hypr/config/defaults.conf

# Autostart wiki https://wiki.hyprland.org/0.45.0/Configuring/Keywords/#executing #

# Gtk Theme workaround
exec = gsettings set org.gnome.desktop.interface gtk-theme Catppuccin-Dark
exec = gsettings set org.gnome.desktop.interface icon-theme Papirus
exec = gsettings set org.gnome.desktop.interface font-name Inter 11
exec = gsettings set org.gnome.desktop.interface cursor-theme catppuccin-mocha-mauve-cursors
exec = gsettings set org.gnome.desktop.interface cursor-size 36
exec = hyprctl setcursor catppuccin-mocha-mauve-cursors 48

# exec-once = swaybg -o \* -i /usr/share/wallpapers/cachyos-wallpapers/Skyscraper.png -m fill
exec-once = /usr/bin/wpaperd -d &
exec-once = waybar &
exec-once = fcitx5 -d &
exec-once = mako &
exec-once = nm-applet --indicator &
exec-once = bash -c "mkfifo /tmp/$HYPRLAND_INSTANCE_SIGNATURE.wob && tail -f /tmp/$HYPRLAND_INSTANCE_SIGNATURE.wob | wob -c ~/.config/hypr/wob.ini & disown" &
exec-once = /usr/lib/polkit-kde-authentication-agent-1 &
exec-once = atuin daemon &
exec-once = nm-applet &
exec-once = /usr/bin/steam &
exec-once = /usr/bin/spotify_player -d &

# ## Slow app launch fix
exec-once = systemctl --user import-environment &
exec-once = hash dbus-update-activation-environment 2>/dev/null &
exec-once = dbus-update-activation-environment --systemd &

# ## Idle configuration
exec-once = $idlehandler
