# ┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
# ┃                     Defaults Configuration                  ┃
# ┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛

$filemanager = dolphin
$applauncher = rofi -show combi -modi window,run,combi -combi-modi window,run
$terminal = kitty --class=kitty_term
$code = kitty --class=kitty_code
$emacs = kitty --class=emacs sh -c emacs
$player = kitty --class=spotify_player sh -c spotify_player -C /mnt/STORAGE/Spotify/Storage/cache
$zapzap = zapzap
$idlehandler = swayidle -w timeout 300 'swaylock -f -c 000000' before-sleep 'swaylock -f -c 000000'
$capturing = grim -g "$(slurp)" - | swappy -f -

# # These are without isolating second GPU
# $priMon = HDMI-A-2
# $secMon = DP-4
# $thiMon = DVI-D-2

# These are with an isolated second GPU
$priMon = HDMI-A-1
$secMon = DP-1
$thiMon = DVI-D-1
