[section/base]
include-file = ~/.config/polybar/base.ini

[bar/left]
monitor = ${env:MONITOR:HDMI-A-0}
inherit = section/bars

[bar/bar]
monitor = ${env:MONITOR:DisplayPort-0}
inherit = section/bars
modules-right = left backlight spacerbg cpu spacerbg memory spacerbg eth spacerbg battery spacerbg pulseaudio spacerbg systray spacerbg dunst right

[bar/right]
; monitor = ${env:MONITOR:DisplayPort-1}
monitor = ${env:MONITOR:DVI-D-0}
inherit = section/bars

;cursor-click = pointer
