[section/base]
include-file = ~/.config/polybar/base.ini

[bar/bar]
monitor = ${env:MONITOR:StSurround}
inherit = section/bars
modules-right = left backlight spacerbg cpu spacerbg memory spacerbg eth spacerbg battery spacerbg pulseaudio spacerbg systray spacerbg dunst right

;cursor-click = pointer

